name: Release

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, linux, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.x

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install NPM packages
        run: cd ui && corepack enable && yarn install --immutable

      - name: Build Release Binary
        run: |
          GOOS=${{ matrix.goos }} GOARCH=amd64 make build
          tar -czvf asynqmon_${{ github.event.release.tag_name }}_${{ matrix.goos }}_amd64.tar.gz asynqmon
          ls

      - name: Upload Release Binary
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh release upload "${{ github.event.release.tag_name }}"
          "asynqmon_${{ github.event.release.tag_name }}_${{ matrix.goos }}_amd64.tar.gz"
          --repo "${{ github.repository }}"
